### ISSUE TITLE
Form name and id - how to add?

### ISSUE THREAD

**Issue by Bratzilla** [LRotherfield/Nibble-Forms#5]
I've been evaluating several form packages to integrate into my custom Joomla projects, and Nibble Forms 2 is definitely on my shortlist. 

There are a couple of issues, however.

1) It doesn't look like the generated form tags have either an id or name attribute. Within a CMS ecosystem, it is very important to be able to tag each form with a unique name and/or id. The id option is very useful when using client-side frameworks such as jQuery.

2) I noticed in the following line in the NibbleForms.php file:  protected $name = 'nibble_form'; 
What if I don't want to use 'nibble_form'? 

I read through the documentation but didn't see anything that specifically addresses this. If there is, could you please point me to it? Thanks!

**Comment by LRotherfield** [comment]
Hi Bratzilla, 

1)The form tags do not have Id or name attributes, at the moment you would just write the form tags yourself if you wanted to add additional attributes.  If you want to create a patch for this then I will be happy to review it.  You can see how to render individual fields under simple usage https://github.com/LRotherfield/Nibble-Forms#simple-usage

2) You can use the setName method: https://github.com/LRotherfield/Nibble-Forms/blob/master/Nibble/NibbleForms/NibbleForm.php#L182 to set the name.

Cheers
Luke

**Comment by Bratzilla** [comment]
Hello, and thank you for your prompt response. The setName method worked well. I did do some minor code modifications to the NibbleForm file. I added $name as the first variable in the main getInstance call (right before $action), and added the id and name attributes to the form tags within NibbleForm as needed. For the id, I just assigned the name value. Yeah, eventually these should probably be separate values.

When I did a post test in my Joomla component, to access that form, all I had to do was access the post variable as follows to get the form values:

$formpost = $this->mainframe->input->getArray($_POST['myform']); 

So far, at least in basic tests, Joomla seems to be getting along with Nibble Forms 2. (I know that J! has its own forms class, but for many reasons I would rather not use it).

Of course, this still needs to be more thoroughly reviewed and tested. Let me know if you want me to pass the code on to you. Overall, though, not much has changed.

**Comment by LRotherfield** [comment]
In order to get the values you should just be able to instantiate the form, call [validate](https://github.com/LRotherfield/Nibble-Forms/blob/master/Nibble/NibbleForms/NibbleForm.php#L222), and then access the data via the [getData](https://github.com/LRotherfield/Nibble-Forms/blob/master/Nibble/NibbleForms/NibbleForm.php#L259) method if the form is [sticky](https://github.com/LRotherfield/Nibble-Forms/blob/master/Nibble/NibbleForms/NibbleForm.php#L242).  The reason I do not require name in the singleton method is because most use cases only have one form so it should not matter what the name is.  In the use case where there is more than one form, the additional forms can call set name but the first still does not have too.

I am glad it seems to be working with Joomla.
