### ISSUE TITLE
TextArea.php

### ISSUE THREAD

**Issue by diquinnyonk** [LRotherfield/Nibble-Forms#7]
I came across issue of the autoloader is looking for Textarea.php and the filename is TextArea.php

On some servers I have used this it does not find the file so would suggest filename becoming Textarea.php

**Comment by LRotherfield** [comment]
Hi Paul,

Thanks for reporting this, did you write:
`$form->addField('text_field', 'textarea');`
rather than:
`$form->addField('text_field', 'textArea');`

The way the files are included is by `ucfirst` the type: https://github.com/LRotherfield/Nibble-Forms/blob/master/Nibble/NibbleForms/NibbleForm.php#L161  so if you don't use a capital 'A' then you will get this issue.

If you have an idea for improving this, please feel free to submit a pull request and I will review it

Cheers
Luke

**Comment by diquinnyonk** [comment]
Apologies for such late reply on here rather than through e-mail. Yes I did all lowercase so perhaps I should've read through your code better. 
Perhaps make a point of this in readme?

I think it's fine the way it is in all honesty. Makes sense, just perhaps a note on it :)
